### ISSUE TITLE
From 2.1.0 components re-rendered if navigating from parent to nested one

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#102]
Dear @ItalyPaleAle,

updating from `2.0.0` to `2.1.0` I have a problem.

```js
const routes = {
  '/': wrap(home, auth),

  '/players': wrap(players, auth),

  '/players/*': wrap(players, auth),
}
```

With `2.0.0` `players` is not updated when I navigate from `/players` to `/players/1` and my `players`'s `onMount` animations are OK.

With `2.1.0` `players` is updated when I navigate from `/players` to `/players/1` and my `players`'s `onMount` animations are repeated everytime.

Is this what you want to happen?

**Comment by ItalyPaleAle** [comment]
I think I understand why this is happening, and it's connected to the fix for #83 

https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Router.svelte#L207-L211

In 2.0.1+, it causes the router to re-render when the component or the params change. In your example above, `/players` has no params, and `/players/*` has the wildcard, so it triggers the IF statement and the re-rendering.

The router is behaving as expected and it's not something I can fix. I saw your comment on #98 but I can't think of a different way to implement this. If you have any idea, I'm happy to accept a PR.

For now, the solution for you might be to use the custom regular expression so you can represent both in the same route:

```js
const routes = new Map()
routes.set('/', wrap(home, auth))
routes.set(/^\/players(\/(.*?))/i, wrap(players, auth))
```

**Comment by frederikhors** [comment]
Too bad. Until `2.0.0` this router was awesome!

**Comment by ItalyPaleAle** [comment]
My apologies, because of a change upstream in Svelte I was forced to make that code change.

Hopefully the solution I proposed above works for you. That should not cause a re-rendering

**Comment by frederikhors** [comment]
Is there some performance decrease using that regex?

This pages are displayed on small HW. Every fps matters.

**Comment by ItalyPaleAle** [comment]
When you use a string in the router, behind the scene it is converted to a regular expression using https://github.com/lukeed/regexparam . For example, `'/players/*'` becomes `/^\/players\/(.*)\/?$/i`

So, it's using a RegEx regardless. Not sure how small that HW is, but at this point, simple regular expressions in JS should be performant enough.

The biggest difference is that you can't use a simple JS dictionary to define your routes, but you need to use a Map.

**Comment by frederikhors** [comment]
@ItalyPaleAle 

`routes.set(/^\/players(\/(.*?))/i, wrap(players, auth))` doesn't work.

**Comment by frederikhors** [comment]
It gets also `/players/`.

But I need all these:

```
/players
/players/123
/players/
```

**Comment by frederikhors** [comment]
The correct one is:

`routes.set(/^\/players(\/(.*))?/i, ...)`

**Comment by ItalyPaleAle** [comment]
You're, right, I should have tested the regex more carefully before sending it to you.

If IDs are only numeric, you can also simplify it as:

```
^\/players(\/([0-9]*))?
```
(this time, I did test it with your 3 cases :) )
