### ISSUE TITLE
Nested routes with param prefix

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#134]
I have this situation:

- / (Home)
- /players - with `const prefix = '/players'` (it works)
  - /players/all
  - /players/create
  - /players/update/:ID
  - /players/:ID - `Open.svelte` (same file)
  - /players/:ID/* - `Open.svelte` (same file)
    - /players/:ID/team
    - /players/:ID/other

In `Open.svelte` what `prefix` should I have?

I tried like this:

```js
const prefix = '/:ID'

const routes = {
  '/': SinglePlayer,
  '/team': Team
  '/other': Other
}
```

It doesn't work? Why?

It only works if I use `const prefix = '/players'` also in `Open.svelte`.

It's weird, right?

I wish I can use `:ID` as prefix.

**Comment by ItalyPaleAle** [comment]
The issue here is that `/players/:id` is actually converted to a regular expression, and that's why using that string as prefix fails.

I've fixed this in version 3.0 (WIP branch, planning to release within a couple of days). The way this will be fixed is by enabling you to define a regular that will be matched as prefix. In your case, you'll define `prefix` as:

```js
const prefix = /^\/players\/(.*?)\//i
```

Once 3.0 is out (or you can try with the [v3.0-wip branch](https://github.com/ItalyPaleAle/svelte-spa-router/tree/v3.0-wip) today!) that will work
