### ISSUE TITLE
Can we avoid repeating the same loadingComponent for each route?

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#142]
I'm using the new 3 version.

I have these routes:

```js
import { wrap } from "svelte-spa-router/wrap";

import RouteLoading from "./RouteLoading.svelte";
import RouteNotFound from "./RouteNotFound.svelte";

export const routes = new Map()
  .set("/", wrap({ asyncComponent: () => import("./Home.svelte") }))
  .set(
    "/todos",
    wrap({
      asyncComponent: () => import("./List.svelte"),
      loadingComponent: RouteLoading
    })
  )
  .set(
    "/todos/:id",
    wrap({
      asyncComponent: () => import("./Todo.svelte"),
      loadingComponent: RouteLoading
    })
  )
  .set(
    "/todos/:id/edit",
    wrap({
      asyncComponent: () => import("./Edit.svelte"),
      loadingComponent: RouteLoading
    })
  )
  .set(
    "/new",
    wrap({
      asyncComponent: () => import("./New.svelte"),
      loadingComponent: RouteLoading
    })
  )
  // ... and so on
  .set("*", RouteNotFound);

```

Can we avoiding repeating: `loadingComponent: RouteLoading` for each route?

In my projects the loader for the routes is always the same component.

**Comment by ItalyPaleAle** [comment]
This was actually by design. There was a conversation [here](https://github.com/ItalyPaleAle/svelte-spa-router/issues/739) and the feedback I got was that people wanted the ability to be able to specify different loading components for different routes. So this is what we have :) I know it's a bit repetitive, but it is the only way (without introducing defaults which I'm really not excited about, as then the API really grows complicated).

**Comment by frederikhors** [comment]
This link (https://github.com/ItalyPaleAle/svelte-spa-router/issues/739) is wrong in your answer.

**Comment by frederikhors** [comment]
This link (https://github.com/ItalyPaleAle/svelte-spa-router/issues/739) is wrong in your answer.

**Comment by ItalyPaleAle** [comment]
Sorry, made a typo. Should have been: https://github.com/ItalyPaleAle/svelte-spa-router/issues/73
