### ISSUE TITLE
Very nested routes quirks

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#144]
I'm trying to use new 3 version.

Reproduction project: https://codesandbox.io/s/svelte-spa-router-very-nested-routes-mskmc?file=/todo/Index.svelte

### Questions:

1. Can we use one regex for this code in `todos/Index.svelte`?

    ```js
    .set("/:ID", Show)
    .set("/:ID/*", Show);
    ```

1. Why do we need to use `const prefix = "/todos"` both in `todos/Index.svelte` and `todos/Show.svelte`? Can we just use `const prefix = "/:ID"` in `todos/Show.svelte`? (https://github.com/ItalyPaleAle/svelte-spa-router/issues/134)

1. Can we avoid `prefix`es at all?

**Comment by ItalyPaleAle** [comment]
1. If you use Maps, you can use a custom regex and actually merge them. So you can just write `.set(/^\/(.*?)(\/(.*?))?/, Show)` instead
2. The prefix has to be relative to the full URL, so the router knows what to exclude from the beginning
3. No, otherwise the router wouldn't match sub-routes correctly

However, in your example, in `todo/Index.svelte` I would argue that I would avoid using a nested router. Because the component doesn't have anything besides a router, I'd instead just put those routes in the "main" router. Nested routers are mostly useful when you want to add markup around the nested router. I wouldn't use them for purely organizing the components...

**Comment by frederikhors** [comment]
1. If I use `.set(/^\/(.*?)(\/(.*?))?/, Show)` **the URL becomes `undefined`** if I clik on "Edit todo" or "Todo notes". Eg: "https://mskmc.csb.app/#/todos/undefined/edit".

2. So I need to have:

    1. `routes.js` with `.set(/^\/todos(\/(.*))?/i)`
    1. `Index.svelte` with `prefix = "/todos"`
    1. `Show.svelte` with `prefix = "/todos"` again

    Am I right?

    **It would be amazing to only have one `prefix = "/todos"` and in `Show.svelte` have `prefix = "/:ID"`**

> in your example, in todo/Index.svelte I would argue that I would avoid using a nested router ... Nested routers are mostly useful when you want to add markup around the nested router. I wouldn't use them for purely organizing the components...

In my `todos/Index.svelte` I have other components. I need nested routers there.

**Comment by frederikhors** [comment]
2. Or at least in `Show.svelte` have `prefix = "/todos/:ID"` because I have a lot of routes, all with: `/:ID` repeated, like this:

```js
const prefix = "/todos";

const routes = {
  "/:ID/": Show,
  "/:ID/notes": Notes,
  "/:ID/services": Services,
  "/:ID/teams": Teams,
  "/:ID/other": Other,
  "/:ID/other2": Other2,
  "/:ID/other3": Other3,
  "/:ID/other4": Other4,
  "/:ID/other5": Other5,
  "/:ID/other6": Other6,
  "/:ID/other7": Other7,
  "/:ID/other8": Other8,
  "/:ID/other9": Other9,
  "/:ID/other10": Other10,
  "/:ID/other11": Other11,
  "/:ID/other12": Other12,
  "/:ID/other13": Other13,
  "/:ID/other14": Other14,
  "/:ID/other15": Other15,
};
```

**Comment by ItalyPaleAle** [comment]
No, a single RegEx is enough. Not sure what the issue there is, but check the docs: https://github.com/ItalyPaleAle/svelte-spa-router#define-routes-with-custom-regular-expressions

As for the prefix... You should be able to define a prefix as a RegEx too. See docs: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#nested-routers

> Note that if your parent router uses a route that contains parameters, such as `/user/:id`, then you must define a regular expression for `prefix`. For example: `prefix={/^\/user\/[0-9]+/}`. This is available in svelte-spa-router 3 or higher.

Is your ID always numeric, or does it follow a specific format? Or can it be any string?

**Comment by frederikhors** [comment]
@ItalyPaleAle I stll don't understand. Sorry. Forgive me.

My reproduction is here: https://codesandbox.io/s/svelte-spa-router-very-nested-routes-mskmc?file=/todo/Index.svelte

## FIRST QUESTION

Can we use only one line (with a regex) for this code in `todos/Index.svelte`?

The problem here is this is a param.

```js
.set("/:ID", Show) // can I have one line only?
.set("/:ID/*", Show) // can I have one line only?
```

If I use `.set(/^\/(.*?)(\/(.*?))?/, Show)` (as you suggested) **the URL becomes `undefined`** if I click on "Edit todo" or "Todo notes". Eg: "https://mskmc.csb.app/#/todos/undefined/edit".

**What I need to use instead?**

## SECOND QUESTION

Why do we need to use `const prefix = "/todos"` both in `todos/Index.svelte` and `todos/Show.svelte`? Can we just use `const prefix = "/:ID"` in `todos/Show.svelte`? (https://github.com/ItalyPaleAle/svelte-spa-router/issues/134)

Now I have:

1. `routes.js` with `.set(/^\/todos(\/(.*))?/i)`
1. `Index.svelte` with `prefix = "/todos"`
1. `Show.svelte` with `prefix = "/todos"` again

**It would be amazing to only have one `prefix = "/todos"` and in `Show.svelte` have `prefix = "/:ID"`**.

**Comment by ItalyPaleAle** [comment]
# First
There was a small mistake in the regular expression I gave you. It doesn't work unless you add `$` at the end.

In `todos/Index.svelte`, your match should be  (note the addition of the $ at the end of the matching sequence)
```
.set(/^\/(.*?)(\/(.*?))?$/, Show)
```

Because the match is using a regexp now, as per the docs I linked above, you can't use `params.ID` anymore as you're doing in the file. Instead, you need to use `params[1]` (because the ID is in the first matched group).

So, in `todos/Show.svelte` you also need to change:

```
<a href={`#/todos/${params.ID}/edit`}>Edit todo</a> | <a href={`#/todos/${params.ID}/notes`}>Todo notes</a>
```

to:

```
<a href={`#/todos/${params[1]}/edit`}>Edit todo</a> | <a href={`#/todos/${params[1]}/notes`}>Todo notes</a>
``` 

# Second question

As I explained above, the prefix has to be relative to the full path being matched. If you're using a double-nested router, you still need to set `/todos` in the prefix.

However, in `Show.svelte` you _can_ set a longer prefix that includes the ID, but:

1. You'll have to use a regular expression for the prefix, so something like `prefix = /^\/todos(\/(.*))?/i`
2. You'll need to remove `/:ID` from the route definition object in `Show.svelte`, so the inner routes will NOT have access to the ID prop

**Comment by frederikhors** [comment]
You've made it really clear now.

Thanks.
