### ISSUE TITLE
Restore Scroll state: missing info in doc?

### ISSUE THREAD

**Issue by vigenere23** [ItalyPaleAle/svelte-spa-router#155]
I've tried to use the `restoreScrollState` feature, but it never worked for me... 

After hours of testing and trying things, I've come to the conclusion that **it only works if using the `push()` function**, and does not work with standard links. As of my understanding, this is because it's impossible to replace the state of the previous location (no `history.popState()` method :cry:) once the `window.location.hash` has changed. So of course this behavior is normal and expected.

All things said, it would be nice to add that info in the `AdvancedUsage` documentation.

P.S.: For those who wonder why I don't just use the `use:link` directive or `push()` methods, that's because I'm using an external library to manage relative vs. external links behavior (manages the `target` correctly and etc.).

**Comment by ItalyPaleAle** [comment]
You're correct that this only works when using pop or use:link. See #52

Sadly this is by design and I don't think this can be changed. You need to add some action to links or it won't be able to save the current scroll position.

I do agree that I should have documented this however. I'll leave this issue open for updating the docs.

**Comment by vigenere23** [comment]
Nice, thanks! But yes, as said, I too don't think it is possible to save scroll position without any other interim call with the current state of Javascript :confused:
