### ISSUE TITLE
Export RouterEvent interface

### ISSUE THREAD

**Issue by vigenere23** [ItalyPaleAle/svelte-spa-router#156]
I think the `RouterEvent` interface in the `Router.d.ts` file should be exported. Else, every callback function gets a `Parameter 'event' implicitly has an 'any' type` warning.

**Version**: `3.0.5`

### Screenshot

![spa-router-implicit-any](https://user-images.githubusercontent.com/32545895/97333168-9ec41400-1851-11eb-9574-69c650c0e5da.png)

**Comment by ItalyPaleAle** [comment]
Uhm when I wrote that, I tested events too and didn't experience this issue.

What is the code that is causing the error? What event are you listening to?

**Comment by vigenere23** [comment]
Sorry, I've just added a screenshot

**Comment by ItalyPaleAle** [comment]
Gotcha. I think I know the issue: if you put the callback directly inside the Svelte markup (eg `on:routeLoaded={(event) => something}`) then the correct type is passed. Because the function is defined separately, this happens.

I don't know if I'd export the RouteEvents interface, because that's a generic. But it could make sense to export an interface for each route event: RouteLoaded, RouteLoading, etc. just like on lines 192-194. 
 they should be easier to use than a generic type.

As I said I'm on vacation right now and don't have my laptop. Want to open a PR?
