### ISSUE TITLE
Cannot use require

### ISSUE THREAD

**Issue by peepopoggers** [ItalyPaleAle/svelte-spa-router#164]
I cannot use require() to import modules like a normal project. Is this to do with the renderer?

If i am mistaken please let me know.

**Comment by ItalyPaleAle** [comment]
Which modules are you trying to import?

In the Svelte ecosystem, almost everything uses ES Modules so you import them with the `import foo from './file'` syntax. CommonJS modules aren't really used with Svelte because they cannot be optimized equally as well.

If you do need to import an external module that is only available as CommonJS module, you should be able to do that as long as your bundler is configured to support that. For example, for Rollup you need to use this: https://github.com/rollup/plugins/tree/master/packages/commonjs

**Comment by peepopoggers** [comment]
Yeah, I was not sure what the problem was exactly, but for anyone having the same issue:

I was using the template 

If you are using electron make sure to add 
```
webPreferences:{
    nodeIntegration: true
}
```
inside of `new BrowserWindow`
for example below the height param.

This allows require to work with svelte and electron.
This wasnt to do with the module but thank you for your help :D
