### ISSUE TITLE
enhancement: set global wrap condition for routes

### ISSUE THREAD

**Issue by ilrico** [ItalyPaleAle/svelte-spa-router#165]
Suppose you have a website that can be accessed directly on any route.
Suppose you need to set a condition on component loading based on a specific state (think user state for instance).
Then you have to define a wrap condition for each route, which can be cumbersome.
It would be nice to define a single wrap condition that applies to all routes.

**Comment by ItalyPaleAle** [comment]
This has been asked before, but I really like a more declarative style for the route definition object and this would start deviating from it.

However, if you really want to avoid wrapping each route, you have 2 options:

1. Create a function that runs `wrap` with your parameters/conditions every time. Example: https://svelte.dev/repl/f75f9eb239ef4f778a275279f3393e17?version=3.29.7 Rather than having to invoke `wrap` on every route, with the same options, you define a `myWrap` function that adds the same options, so then you just need to use `myWrap` with each route
2. Define the route object without wrapping, then iterate through each key to add the wrap: https://svelte.dev/repl/4a07b2837d4f462cb32daf73949eb265?version=3.29.7
