### ISSUE TITLE
Request: support top-level component props

### ISSUE THREAD

**Issue by NfNitLoop** [ItalyPaleAle/svelte-spa-router#183]
Right now, it seems to be required that you have a single component property called `params` on your components to be able to route to them.

For example:

```
const routes = {
    '/:foo/:bar': MyComponent
}
```

requires a component that declares:

```
export let params = {};
```

And accesses the values via `params.foo` and `params.bar`.

But that makes your component's design tightly coupled with svelte-spa-router. If I have a component that's designed to be generally reusable, with parameters like this:

```
export let foo = "some default foo"
export let bar = "some default bar"
```

... there doesn't seem to be a great way to bridge the gap between what is required by svelte-spa-router, and what is expected by general-purpose svelte components.

**Comment by ItalyPaleAle** [comment]
I tend to agree with your thoughts on the fact that this is coupled and the alternative design would be better in theory.

The problem is that Svelte components don't export parameters as properties unless they're compiled as Web Components ([docs](https://svelte.dev/docs#Component_props)) so this was not something we could implement easily.

The other problem is that, even if it could be possible to implement this nicely, it would be a major breaking change. In the history of this project, I've always been very careful to limit the number of breaking changes and especially their potential impact: this would affect every user and potentially require major code changes. Your points above are totally valid, but they are still more on the cosmetic side. For a breaking change of this magnitude, I'd need a very strong case, and I don't think this is strong enough.

In your case, you could always do a fallback. For example:

```js
export let params = {}
export let foo = "default"
$: foo = params && params.foo
```

Which will ensure that foo is automatically updated if `params` is updated.

**Comment by NfNitLoop** [comment]
One wrong path I went down to try to make a component that works well for both svelte-spa-router and standalone usage:

```javascript
export let params = {
    foo: "some default foo"
    bar: "some default bar"
}
export let foo = params.foo
export let bar = params.bar
```

This works on first render, but, if the params get updated (ex: by changing foo or bar in the URL), the top-level `foo` and `bar` do not.  If you modify `foo` and `bar` to be reactive, you're back in the original situation where `foo` and `bar` are no longer assignable component parameters.

🤔 Hmm, I suppose you could do this:

```javascript
export let params = {
    foo: "some default foo"
    bar: "some default bar"
}
export let foo = params.foo
export let bar = params.bar

$: {
    foo = params.foo
    bar = params.bar
}
```

So... (aha, you commented before I could finish writing this).  So there is a way to design my component to be usable both ways, which is OK, but it does mean that you still have to specifically design your components to be usable this way.

**Comment by NfNitLoop** [comment]
> this was not something we could implement easily.

Admitting ignorance here, as I'm new to Svelte, but aren't components just created with `props` option? Couldn't there be a way to opt-in to sending params directly to those props?

> The other problem is that [...] it would be a major breaking change

I didn't propose breaking the old behavior. There could be an opt-in way to do this kind of prop forwarding, something like the existing `wrap` functionality.

**Comment by ItalyPaleAle** [comment]
I think this should work, although I haven't tried it! I would just make two suggestions:

1. `export let params = {}` -> Don't assign default values to that because they will be ignored anyways
2. I think it's better to have two lines such as:
   ```
   $: foo = params && params.foo
   $: bar = params && params.bar
   ```
   This is so the reactive statement isn't triggered if `foo` or `bar` change (I've seen Svelte having some weird behaviors there)

If your goal is to have a component work in both svelte-spa-router and standalone, you can also simply consider wrapping your component into another one.

For example, assume you have a component `Foo` that exports proeprties `foo` and `bar`. Rather than adding `Foo` itself to the router (in the route definition object), you create a component called `FooRoute` that contains this:

```svelte
<Foo {foo} {bar} />
<script>
export let params
$: foo = params && params.foo
$: bar = params && params.bar
</script>
```

Then you use `FooRoute` in the route definition object.

**Comment by NfNitLoop** [comment]
re: wrapping components ... yes, I'd had that idea as well. But requiring a wrapped component for every component I might want to route to seems like a lot of extra boilerplate and indirection, no?

**Comment by ItalyPaleAle** [comment]
Well, yes. But it depends on how many components you need wrapped too!
