### ISSUE TITLE
Package no longer works in the official REPL

### ISSUE THREAD

**Issue by proamlive-admin** [ItalyPaleAle/svelte-spa-router#220]
https://svelte.dev/repl/6e7546119cff41fabe35df3ef999ff7e?version=3.29.4

This example and all my snippets are now broken, not sure when it happened but yeah...

**Comment by ItalyPaleAle** [comment]
Thanks for reporting this.

Looks like the Svelte REPL always uses the latest version of NPM modules, rather than looking at what's in package.json. Our only dependency, regexparam, was recently updated to support ESM, but that was a breaking change (in fact they bumped to version 2). package.json pins version 1.3, but that is ignored by the REPL.

Bottom line: I need to update regexparam to version 2. Should be a relatively straightforward change; I'll do it shortly.
