### ISSUE TITLE
Component not shown after redirect

### ISSUE THREAD

**Issue by JiProchazka** [ItalyPaleAle/svelte-spa-router#229]
Hi,

I'm trying to do a redirect:

```
export const routes = {
  // Exact path
  "/dashboard": Dashboard,

  "/": wrap({
    component: Dashboard,
    conditions: [
      () => {
        return replace("/dashboard");
      },
    ],
  }),

  // Catch-all
  "*": NotFound,
};
```

But when I type `http://localhost:8086` the url gets correctly replaced with `http://localhost:8086/dashboard`, but the component is not loaded/shown, only after F5 page reload.

I guess I have the redirect defined wrong?

Thanks

EDIT:
When I type `http://localhost:8086` it get redirected correctly. But when I type `http://localhost:8086/#/` the problem appears.

**Comment by ItalyPaleAle** [comment]
Conditions are meant to be synchronous functions that return a boolean true or false. They're not the place to do redirects, because that will interfere with the sequence of operations (there's things that need to run on iterations of the event loop, etc).

You have two options:

1. Use a condition that returns false, and then do the redirect in the [`conditionsFailed`](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#route-pre-conditions) handler
2. Use the [`routeLoaded`](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#routeloading-and-routeloaded-events) handler.

**Comment by JiProchazka** [comment]
Ok, got it! Thanks!
