### ISSUE TITLE
How get the previous location, i.e. from where we get ?

### ISSUE THREAD

**Issue by LeoFlandin** [ItalyPaleAle/svelte-spa-router#239]
`import { location } from "svelte-spa-router";` can give you the current location and this is great.
I'm find myself wanting to know where I'm coming from.
Is there a `import { previousLocation } from "svelte-spa-router";` ?

The reason I'm looking for this is because I need to manage Svelte transition from the transition PoV and not from the Component (State) PoV. 
A transition A -> B would not be the same as A -> C

**Comment by ItalyPaleAle** [comment]
This can't be done in the router, because the router's state is managed by the browser's history, and JavaScript apps can't access the pages that users visited beforehand. Essentially, if I were to implement this, it wouldn't survive page reloads, and users wouldn't be happy :)

Your best bet is to use a route event (such as `routeLoaded`) and maintain a stack of pages viewed in memory. This will need to be code that is part of your application.
