### ISSUE TITLE
Pages get stacked when using svelte transition

### ISSUE THREAD

**Issue by hcrohland** [ItalyPaleAle/svelte-spa-router#241]
Hi,

I have a Svelte app using the svelte-spa-router. The main page consists of an grid of bootstrap cards which are instantiated with svelte transition:slide. If I switch from the main page  to another page the main page often - but not always - does not disappear. Instead the new page is rendered below the existing page. This can even happen multiple times stacking pages on pages.

If I remove the transition from the cards all works fine. 

I tried to replicate this with a simple example to no avail so far. So sorry for the

**Comment by ItalyPaleAle** [comment]
Can you please share some code to reproduce the issue? I'm afraid, without it will be impossible to debug this.

**Comment by hcrohland** [comment]
Okay, found a second condition: It needs to also use and modify a store between pages.

And here is a REPL to replicate: https://svelte.dev/repl/2897c6f2cee7479fa41416e93ce75970?version=3.43.0

**Comment by ItalyPaleAle** [comment]
This is very helfpul.

However, looks like this is not an issue with the router itself, but an issue upstream with the Svelte compiler.

I was able to replicate the issue here without using the router: https://svelte.dev/repl/193b233e492c4c75b0d0fd07604c7165?version=3.43.0

In particular, this only happens when you set a component with `<svelte:component this={page} />` and not if you set the component directly (such as `{#if page == 'xx'} <Page1 /> {/if}`).

Would you mind opening an issue with the Svelte team directly? Hopefully what I found above can help them too :)

**Comment by hcrohland** [comment]
Opened a bug with the svelte team: https://github.com/sveltejs/svelte/issues/6779

**Comment by ItalyPaleAle** [comment]
Thank you! I also just noticed that my use of `setTimeout` (which I added trying to figure out what could cause the issue, building iteratively adding things that svelte-spa-router uses) wasn't necessary, so I removed it from the REPL.

**Comment by abezulski** [comment]
I had exactly the same issue using nested routing, store and transition - navigation between categories /#/listings/active or /#/listings/expired was fine, but navigating to main page /#/listings and back to category would result in stacked pages. My workaround to this issue was to remove nested routing (explained here: https://github.com/ItalyPaleAle/svelte-spa-router/issues/20#issuecomment-929581845).

**Comment by algaly** [comment]
Try replacing your a tag with button and use the push method.
Worked for me! (even with animation)

**Comment by michaelphipps** [comment]
The button method didn't work for me, however I found this https://github.com/sveltejs/svelte/issues/6226#issuecomment-1285744046 that provided a workable solution

> ... another solution I came across is adding |local to the out animation.

```
<div
  in:fly="{{ y: -100, duration: 200 }}"
  out:fly|local="{{ y: 100, duration: 200 }}"
>
```
