### ISSUE TITLE
Routes open at bottom of page

### ISSUE THREAD

**Issue by cabreraalex** [ItalyPaleAle/svelte-spa-router#26]
Not sure if this is a bug or I implemented something wrong:

When I click on a link, it opens the new route wherever the original view was. You can recreate this on my website: at cabreraalex.com, scroll to the bottom and click on the title "Discovery of Intersectional Bias in Machine Learning Using Automatic Subgroup Generation". The new page route opens at the bottom.

Thanks!

**Comment by ItalyPaleAle** [comment]
When you say that, do you mean that when the page updates, it's not scrolled all the way up as you'd expect?

If so, this is a good point. It's not a feature of the router at the moment, because I try to be as lean as possible, and doing that might break some people's code. You could implement this with an [`onMount`](https://svelte.dev/docs#onMount) callback that invokes `window.scrollTo(0,0)`

**Comment by cabreraalex** [comment]
Yup exactly! That's a good point, didn't about most single page apps not wanting it to act that way. I'll try that!

**Comment by ItalyPaleAle** [comment]
I think it might apply to others, but it really depend on the app. You're the first one asking for this, but let's see what happens next :)

**Comment by cabreraalex** [comment]
`onMount(() => window.scrollTo(0, 0));`
works like a charm, so at least others can easily fix it for now. 

Thanks, really liking this router :)
