### ISSUE TITLE
when using "use:link" middle click will not work

### ISSUE THREAD

**Issue by wolfispace** [ItalyPaleAle/svelte-spa-router#33]
When using the "use:link" option and i want to open the link in a new tap (middle click in the mouse) it will open as /book/321 instead of /#/book/321.

`<a href="/book/321" use:link>The Little Prince</a>`

**Comment by TorstenDittmann** [comment]
Could this be solved by looking for the missing hash and additionally maybe the length of `window.history`?

**Comment by TorstenDittmann** [comment]
Created a Pull request that handles middle clicks like normal clicks => #34

**Comment by ItalyPaleAle** [comment]
@TorstenDittmann thanks for the PR.

I've been thinking about this, and I'm wondering if the best way would actually be to change the handler so it actually modifies the `href` element rather than waiting for a click? Otherwise, we'd have to support a lot of cases, such as middle button click, right-click and then "open in new tab", etc...

Thoughts?

**Comment by TorstenDittmann** [comment]
Okay, that makes more sense. 

Updated my PR for a proposed solution, where every link gets the `#` in the `href`.

**Comment by avimar** [comment]
I think this is the same issue?

`<a href="/line/{line.id}" use:link>`

When I control or shift click, to open in a new tab or new window, it just opens it in the same tab.

If I use `<a href="#/line/{line.id}">` then it seems the router works properly and there's no extra page loads from a full refresh.

Is this a bug to be fixed?
