### ISSUE TITLE
Can't SSR render SPA for SEO?

### ISSUE THREAD

**Issue by hmmhmmhm** [ItalyPaleAle/svelte-spa-router#41]
I understand that this module uses CSR(Client Side Render),
However, search engines in some countries still cannot analyze CSR pages.

Of course, for of the SEO(Search Engine Optimization),
It might be better to use the Sapper.
SSR does not easily fit the structure of Cordova or Electron.

In my opinion, if there is a separate module that renders SPA,
it will be more convenient for all platforms to be compatible at once than Sapper.

Have anyone ever configured an SEO server for this module?
I want to create a separate server module or template for performing SSRs for SPA.
I'd like to know if someone have any ideas for a better direction.

**Comment by ItalyPaleAle** [comment]
Hey @hmmhmmhm I am aware of the fact that search engines don't always crawl SPAs correctly. However, the focus on client-side rendering is the reason why I created this router and I am not interested in adding support for SSR. In fact, I created this router specifically because the one I was using with Svelte 2 dropped support for hash-based routing when migrating to Svelte 3. There are other routers for Svelte 3 that are optimized for SSR (aside from Sapper, actual routers), so there's choice. 

If perfect SEO is a concern for you and you need SSR, then I would say this module simply isn't for you. There are many situations where SEO doesn't matter (e.g. SaaS apps that require authentication) or where developers are satisfied with search engines' capabilities for crawling their apps even when using client-side routing.

The problem with SSR is that it... requires a server. And so you can't deploy the apps to static website hosters, or IPFS, or...

**Comment by hmmhmmhm** [comment]
I understand. But I'm sure there are some people who go through unavoidable situations like me. (I also try using IPLD and IPFS.. Yes it's perfect serverless except the gateway. And sometimes I use AWS because of uploads that are sometimes too slow. At this time, I'm just thinking about this for a while. Because There's a problem with Korean search engines not able to search my web app.) I will look for a separate way to render the CSR app.
