### ISSUE TITLE
How to forward events with router and nested routes?

### ISSUE THREAD

**Issue by rottmann** [ItalyPaleAle/svelte-spa-router#42]
View https://svelte.dev/tutorial/event-forwarding

**Comment by ItalyPaleAle** [comment]
Could you please give me an example of what you're trying to achieve? You have a route (let's call it `MyRoute`) that is triggering an event, and you want the `Router` component to forward it up to the `App` (main) component?

**Comment by rottmann** [comment]
Exactly.

**Comment by ItalyPaleAle** [comment]
Sorry for the delay in responding.

I don't think this is possible. In Svelte, events don't bubble up the chain, as per design: https://svelte.dev/docs#createEventDispatcher

You need to find a workaround to this. Some ideas:

1. Rather than using Svelte's events, dispatch your own CustomEvents attached to a DOM node like `document`: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events
2. Rather than using events at all, invoke a method defined in the global scope (or exported by a ES module)
3. Another option is to use a Svelte writable store and watch for value changes reactively: https://svelte.dev/tutorial/writable-stores

**Comment by rottmann** [comment]
Thanks for your reply. Currently i use this method for global event transactions and event-forwarding only for local connected components.
