### ISSUE TITLE
[Bug] Hashchange happens when route guard fails

### ISSUE THREAD

**Issue by aarongeorge** [ItalyPaleAle/svelte-spa-router#45]
**WHEN** clicking a link such as this: `<a href='/' use:link>Home</a>` from any route other than `/`
**IF** there is a route guard
**AND** the route guard fails
**THEN** the hashchange event fires
**CAUSING** any transitions on the current page to fire again as the page is re-rendered

**EXPECTED** The hashchange event does not fire
**AND** transitions are not re-triggered as the page is not re-rendered

**Comment by ItalyPaleAle** [comment]
If I understand the issue correctly, this is actually by design.

Route conditions are executed before the component is loaded (ie. it's injected in the DOM). This happens as a result of an "hashchange" event. If the pre-conditions fail, then a "null" component is loaded (that is: nothing is loaded), and *then* the app can display another component by using `replace()` (for example) in the `conditionsFailed` event listener.

It is not possible to get route conditions executed before the hashchange event, because that's how the router handles navigation. In fact, `use:link` is one way to trigger a route change, but apps can create "hash-links" directly (e.g. `<a href="#/">`), and users can also type the URL in the browser's navigation bar... Conditions need to be executed in all these cases.

Does it make sense? If you want to provide more details, any chance you could produce a [REPL](https://svelte.dev/repl)?

**Comment by aarongeorge** [comment]
Oh okay, so it is not possible to prevent the hashchange from happening until after the route guards have been run?

From my way of looking at it, a route guard should prevent navigation to it unless the validations pass.

I understand this doesn't really work when putting the direct path in the browser url bar, but using the link and navigate/replace methods should function this way

**Comment by ItalyPaleAle** [comment]
The way you should think about route conditions/guards in this route is that they prevent the component to be loaded (ie  injected in the DOM). This is quite similar to how server-generated pages work, eventually: first you request the page, and then you might get an error or redirect.

I’m afraid that having different behaviors depending on the way a link is created and clicked on would add inconsistencies in the experiences, for developers and end users, and I’d prefer to avoid that.
