### ISSUE TITLE
Just one wildcard route for nested routes?

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#48]
It would be amazing to have just one route declaration for this case.

As it's now:

```js
routes = {
  '/books': Books,
  '/books/*': Books,

  '*': NotFound,
}
```

It would be amazing this:

```js
routes = {
  '/books*': Books,

  '*': NotFound,
}
```

In `Books` component I have these routes:

```js
routes = {
  '/books': Index,
  '/new': NewBook,
  '/show': ShowBook,
}
```

Now it doesn't work, right?

**Is it possible? Am I wrong and this is not good?**

**Comment by ItalyPaleAle** [comment]
See here for nesting: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#nested-routers

**Comment by frederikhors** [comment]
@ItalyPaleAle I have read all about that.

The issue (exposed not very clearly, I admit) is this:

If I need to handle an URL like: `mydomain.com/#/books` (without final slash `/`) I need two routes like this:

```js
routes = {
  '/books': Books,
  '/books/*': Books,
}
```

Is there a way to handle both `#/books` and `#/books/*` with just one route?

Is it clear now?

**Comment by ItalyPaleAle** [comment]
You can totally do `/books*` but that would lead to unexpected consequences, such as matching `/booksmart` too. Hence the recommendation to use both `/books` and `/books/*`, which comes from https://github.com/lukeed/regexparam (the library used to parse the strings)

Having to define the route twice is an annoyance, but it should be a relatively minor one...

If you absolutely needed to define the route only once, you should look into defining it using a custom regular expression, which however requires using maps rather than objects with this router. With your example:

````js
const routes = new Map()
routes.set(/^\/books(\/(.*))?$/i, Books)
````
