### ISSUE TITLE
Route pre-conditions promises

### ISSUE THREAD

**Issue by rottmann** [ItalyPaleAle/svelte-spa-router#53]
Pro-Conditions should resolve promises.

Before a route is called, i load settings async from a local storage and check user token async on a server before i route the user to the target page.
In the meantime i show a "Please wait" screen.

**Comment by ItalyPaleAle** [comment]
Hi @rottmann I am not looking at adding support for async conditions, because that would require adding a way to show a route while the condition is resolving... A mess!

My suggestion for you is to skip using route conditions and instead use another Svelte component as wrapper that controls the loading of the route.

For example, if your component is `Foo`, create a component called `Wrapper` that shows `Foo` only after a promise is resolved. In the router, you'd add `Wrapper` rather than `Foo`.

**Comment by CraigBanach** [comment]
@ItalyPaleAle I think you should add a similar comment to the Advanced Usage -> pre-conditions section. This would have helped me out.
