### ISSUE TITLE
Open modal with dedicated route (URL)

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#58]
Something that I can't find and that is still missing today is a mechanism to open modals with a dedicated URL.

Example:

```js
const routes = {
  '/players': PlayersList,
  '/players/:playerID/edit': PlayersList
}
```

- I'm on listing page (URL: `/#/players`)
- I click on a row with ID 4
- the function `handleRowClick()` in `PlayersList` component:
  - push a new URL: `/#/players/4/edit`
  - check for `$location`:
    - if `/edit` is present: open modal
    - if not: return

Does this make sense?

Just one problem with this today. Using this function:

```js
async function handleRowClick (playerID) {
  await push(`/players/${playerID}/edit`)
  await console.log('$location is:', $location) // not the new one, still the old one: /players
  await tick()
  await checkLocation()
}

async function checkLocation () {
  await tick()
  await console.log('$location is:', $location) // not the new one, still the old one: /players
}
```

If I click the same row or another one (different ID) the `$location` now is the old (not anymore new) one (`/players/4/edit`).

How is it possible?

**Comment by ItalyPaleAle** [comment]
I think the issue is that `push` is not an async function. You shouldn't "await" for push because it doesn't return a promise.

Instead, you should listen to the [`routeLoaded` event](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#routeloaded-event) to see when the page has changed.
