### ISSUE TITLE
A function that repeats only on each page?

### ISSUE THREAD

**Issue by hmmhmmhm** [ItalyPaleAle/svelte-spa-router#68]
What is the simple way to configure setTimout or setInterval that works whenever each page is activated without waste in the event handler?

**Comment by hmmhmmhm** [comment]
![스크린샷 2019-11-19 오후 3 24 58](https://user-images.githubusercontent.com/38493722/69121921-ce668a00-0ae0-11ea-9a6e-1918cda5a3b7.png)

Is it okay if I send a PR to embed these functions into the library?

**Comment by ItalyPaleAle** [comment]
This (listening on the $location store) is definitely a way. Another way (which might be better if you want to listen to changes on $querystring too) is to use the “routeLoaded” event and place the timeout on the callback.

As for opening a PR, why do you think this would be best in the router rather than in the users’ code? What problem are you trying to solve that would be best implemented in the router? As you know, I’m trying to keep the router lean and implement in there only things that can’t be done in any other way.

**Comment by hmmhmmhm** [comment]
I think it's better to provide some of the functions involved in the task that work uniquely on each page. Isn't convenience the most important thing? (like a svelte?) If you don't like the idea of embedding this feature in the module, I think it's okay to just put it in my svelte-spa-chunk.

**Comment by ItalyPaleAle** [comment]
svelte-spa-router is meant to be included in many different apps and, since it's front-end code, every bit of it gets shipped to clients. It's very important that we keep this lean and minimal, for speed, maintainability, reliability and security.

My "litmus test" for deciding on what goes in the router is that things get included if all these are true:

1. If it's not possible (or much more inconvenient) to achieve the same result if the code isn't part of the router itself
2. If it's a feature that would benefit a significant number of user.
3. The APIs are generic enough and not overly complicated

I'm afraid a PR like this would violate the condition 1, as it could be implemented in the app's code with just few lines of code:

````svelte
<Router on:routeLoaded={routeLoaded} />
<script>
import { onDestroy } from 'svelte'
let interval = null
function routeLoaded(event) {
    if (interval) clearInterval(interval)
    interval = setInterval(something, 1000)
}
onDestroy(() => clearInterval(interval))
</script>
````

I'm also not sure about condition 2, as it seems something very specific to one use case
