### ISSUE TITLE
Maybe a bug with a modal

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#75]
I don't know if this problem is with `svelte-spa-router` or with `sveltestrap`.

### Reproduction here: https://codesandbox.io/s/modern-cache-znqt3

But codesandbox is not the best place for routing issues.
You can download project: "File > Export to Zip".

### The problem

Reproduction steps:

1. Click on "Hello" menu item
1. Click on button
1. Modal should appear
1. Click on the back button of the browser
1. The problem is "Hello Home" and button are still there (on codesandbox the modal too).

Using `{prefix}` incredibly fix the issue but I don't know why and I suspect a bug.

![image](https://user-images.githubusercontent.com/41120635/71774024-b4d1b280-2f67-11ea-9b68-7b354c744067.png)

**Comment by frederikhors** [comment]
Sveltestrap's author is trying with me to understand the problem here: https://github.com/bestguy/sveltestrap/issues/105.

**Comment by ItalyPaleAle** [comment]
Hi are you still having this issue? Can you please share a repro?

**Comment by ItalyPaleAle** [comment]
Were you able to fix this issue?

**Comment by hmmhmmhm** [comment]
I know exactly where this is a problem and how to fix it.

The css transition of the svelte requires the use of the
same bundle when used between external components.

The current import code is as follows.

```js
import { Modal, ModalBody, ModalHeader } from "sveltestrap";
```

Modifying the above code as shown below will solve the problem.

```js
import { Modal, ModalBody, ModalHeader } from "sveltestrap/src/index.js";
```

This problem is svelte's problem, so there are common errors in all bundlers.
(Rollup, Parcel, Webpack anythings....)

You can see this problem when you use smelte or svelma or
sveltestrap. (because modal is an example of using nested css transition.)

**Comment by ItalyPaleAle** [comment]
Closing as this doesn't seem to be an issue with the router. Thanks all for the great discussion!
