### ISSUE TITLE
Named Params not working as expected

### ISSUE THREAD

**Issue by Baudin999** [ItalyPaleAle/svelte-spa-router#76]
I am trying to get the named params to work, I have a set of routes:

```
const routes = [
  { name: "/project/:projectName/details", component: ProjectDetails }
];
```

I am trying to keep the routs as simple as possible. What I would expect is that the URL:

```
http://localhost:5000/project/Something/details
```

What I get as the `currentRoute` is:

```
{
    "name": "/project/details",
    "component": "",
    "queryParams": {},
    "namedParams": {
        "projectName": "details"
    },
    "path": "/project/Something/details"
}
```

What I would expect is:

```
{
    "name": "/project/:projectName/details",
    "component": "",
    "queryParams": {},
    "namedParams": {
        "projectName": "Something"
    },
    "path": "/project/Something/details"
}
```

Am I doing something wrong? If needed I can try and create an example to reproduce.

**Comment by ItalyPaleAle** [comment]
I don't think you're doing something wrong per se, it could be a bug in the upstream package that we use to parse arguments.

I think you have 2 possible (easy) workarounds here:

1. Use a nested router within `/project/:projectName`
2. Define your path using a regular expression rather than a string

**Comment by Baudin999** [comment]
OK, will try it another way
