### ISSUE TITLE
Investigation for a smooth and fast UI, doubts and proposal

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#77]
This Svelte router is amazing! I'm very happy using it.

And it's because I love it that I want to try to improve it even more!

# Issue

Many projects has heavy pages with heavy scripts.

I need a smooth and fast UI with immediate feedback when I change page.

# One possible solution

As you can read here: https://github.com/sveltejs/svelte/issues/2979 about a year ago I asked for something similar to the authors of Svelte.

A few hours ago @jacwright suggested using `requestAnimationFrame` instead of `setTimeout` (https://github.com/sveltejs/svelte/issues/2979#issuecomment-587979989).

```js
export async function awaitFrames (count = 1) {
  for (let i = 0; i <= count; i++) {
    await new Promise(requestAnimationFrame)
  }
}
```

```svelte
onMount(async () => {
  await awaitFrames(2);
  mySlowFunction(10);
  loaded = true;
});
```

I still don't know if this is the best solution for the problem.

**Is there anything better that can be done?**

# Proposal

I'm wondering if it is possible to equip `svelte-spa-router` with similar native functionality to avoid repeating the same code on each page.

Maybe a dedicated component called e.g. `Page.svelte`?

# Reproduction

Live example: https://codesandbox.io/s/investigation-for-a-fluid-ui-bhknp.

As you can see if you click on:

1. **Light page**:
    1. when you click it loads immediately!

1. **Hard page**:
    1. when you click the page freeze
    1. slow CPU intensive work goes on and
    1. only after that Svelte renders the page

1. **Hard page with rAF**:
    1. when you click the page loads immediately
    1. after that the CPU intensive work begins
    1. after that CPU work the `loaded` var is set to `true`

---

Thanks again for your amazing work! :)

**Comment by frederikhors** [comment]
@jacwright, it would be a pleasure to read your opinion about it.

**Comment by frederikhors** [comment]
@PaulMaly, it would be a pleasure your opinion too having seen your beautiful work here: https://github.com/PaulMaly/svelte-viewpoint.

**Comment by PaulMaly** [comment]
@frederikhors Hi, I'm not using svelte-spa-router and actually not sure I clearly understand all doubts about it. It's pleasant to hear your feedback about svelte-viewpoint but it's the router agnostic loadable component. It means you can switch target components in any way you like.

**Comment by frederikhors** [comment]
@PaulMaly and what do you think about `requestAnimationFrame` for non-blocking component loading?

**Comment by TorstenDittmann** [comment]
Mhh, I really like the idea of it. But, I don't think the router should be the one to handle this.

If you have heavy load components like in your example, it should be handled by the component - not the router IMO.

**Comment by ItalyPaleAle** [comment]
Hi @frederikhors can you help me understand your issue with a large page, and how this would help? I'm not really sure what you're trying to accomplish?

**Comment by frederikhors** [comment]
@ItalyPaleAle sorry for the perhaps too long message.

Can you open this live example?

https://codesandbox.io/s/investigation-for-a-fluid-ui-bhknp

> As you can see if you click on:
> 
> 1. **Light page**:
>     1. when you click it loads immediately!
> 
> 1. **Hard page**:
>     1. when you click the page freeze
>     1. slow CPU intensive work goes on and
>     1. only after that Svelte renders the page
> 
> 1. **Hard page with rAF**:
>     1. when you click the page loads immediately
>     1. after that the CPU intensive work begins
>     1. after that CPU work the `loaded` var is set to `true`

I don't know if the router can automagically use `requestAnimationFrame` on `onMount()` to render pages.

What do you suggest?

**Comment by hmmhmmhm** [comment]
I have solved these problems at my way (in my projects).
(currently i'm using svelte-spa-router in my production apps).

First of all, as reflected in the advanced usage,
I created an (asynchronous) dynamic import module called svelte-spa-chunk.
(Here I used svelte-loadable as you suggested like a waypoint.)

And as you predicted, one problem arose when i
had to bring all the pages in asynchronously.

My service had a problem of briefly exposing white pages
because until recently my service page was called
by dynamic import through code splitting.

To fix this issue, I first set it up through the svelte css transition
so that the previous page remains as if it were an afterimage
until the new page was loaded through svelte-loadable .

( https://github.com/hmmhmmhm/svelte-spa-chunk/blob/master/Chunk.svelte#L10 )

And I created a postbuild script to create a prefetch link of
all resources and connect them to index.html so that all pages'
code splitting files can be downloaded automatically during the browser's IDLE time.

( https://github.com/hmmhmmhm/svelte-spa-template/blob/master/postbuild.ts )

Through these tasks I was able to render all the pages softly.

**Comment by jacwright** [comment]
@frederikhors, Svelte is great because you can create your own components. Rather than adding anything to a particular routing library, why don't you create a component that does what you are looking to do?

E.g. you suggested a Page component.

`Page.svelte`
```html
<script>
import { onMount } = 'svelte';
export let component;
export let wait = 1;
export let props;
let load = false;

onMount(async () => {
  await awaitFrames(wait);
  load = true;
});

async function awaitFrames (count = 1) {
  for (let i = 0; i <= count; i++) {
    await new Promise(requestAnimationFrame)
  }
}
</script>

{#if load}
<svelte:component this={component} {...$$props}/>
{/if}
```

```html
...
<h1>My Page</h1>
<Page component={SomeHeavyLoadingComponent} wait={2}/>
```

And of course, since it is your Page component, you can add in loading animations, nest "pages", rename it to Delay.svelte if you want, wrap it in some HTML and style it, whatever!

**Comment by ItalyPaleAle** [comment]
@hmmhmmhm and @jacwright provided great insights and help (thanks both!!)

I still think this is something best solved by a custom component (an intermediate component that loads your routes), rather than on the router itself.

**Comment by frederikhors** [comment]
@ItalyPaleAle @jacwright this is similar to what I thought: https://github.com/trambarhq/relaks.

It's for React / Preact and I only found out today.

**Comment by frederikhors** [comment]
This is the router: https://github.com/trambarhq/relaks-route-manager.

**Comment by frederikhors** [comment]
Look at [Trambar demo](https://github.com/trambarhq/trambar/blob/master/docs/demo.md). Amazing smooth navigation between routes!
