### ISSUE TITLE
Remove Hash

### ISSUE THREAD

**Issue by christopherbecker** [ItalyPaleAle/svelte-spa-router#88]
Hi,

First of all, good job with this package it works really well.

I have a question, is there any way to get rid of the hash. I've read the documentation and I could only find that it is a hash based router.

Thanks,

Christopher

**Comment by ItalyPaleAle** [comment]
Hi there, the hash is actually a feature of this router.

There are two ways to do client-side routing:

- Hash-based, which is also the older one. This works because when you change the hash of the page, browsers add a new entry in the history. We've been doing this for a VERY long time (the first "AJAX web apps" were using this technique!), but that doesn't mean it's outdated: GMail uses hash-based routing, among others
- Using the [HTML5 History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API). This is a more modern, but at this point widely supported, approach, in which JS apps can push fake URLs in the browser. There's no hash here.

The problem with the HTML5 History API is that browser might load a page that doesn't exist. For example, if you navigate from `/` (which in reality is `/index.html`) to `/page2`, the navigation will work in the SPA. But, the URL doesn't exist on the server, so if you try to refresh the page, or if you share the link with someone else, you'll get a 404 error.

The solution to that problem is to do some routing on the server-side too. But this is not always possible: if you deploy your app on object storage, on IPFS, or simply on servers that don't understand the behavior you're looking for, it won't work. It can also reduce the ability to cache pages in a CDN.

This is the reason why I wrote this router. There are other [Svelte routers](https://github.com/sveltejs/svelte/wiki/FAQ#is-there-a-router) that support the HTML5 History API. This one, does not, by design, as the problem we're working with is a different one :)
