### ISSUE TITLE
(ONLY 2.0.1) Component recycling issues when routing with parameters

### ISSUE THREAD

**Issue by hmmhmmhm** [ItalyPaleAle/svelte-spa-router#90]
## Issue Overview

Components with parameters, such as /route/:id, are reused.
2.0.0 does not cause this reuse, but it does occur at 2.0.1 .

## How to reproduce

```bash
git clone https://github.com/hmmhmmhm/broken-spa-example
npm install && npm start
```
And you can check localhost url,
If you enter to that url, you will see a yellow window (yellow Routing Path: `/a`)
Now click on the yellow window to switch to the blue window (path to blue: `/b/blabla`)

And click on the blue window and the script tries to move to /a.
However, routing fails and the screen switches to white screen.

When you exit the project and use the command below to
downgrade and re-run it, you can see that none of these issues occur.

```bash
npm install svelte-spa-router@2.0.0 && npm run postinstall && npm start
```

And if you only route to /b instead of /b/blabla, you'll see that this issue doesn't happen.

## Issue Detail

I am currently developing a structure in
which page components are should not be reused during routing.

My pages are loaded asynchronously.
So inevitably there was a white HTML DOM exposure
until the js file with new page information was completely downloaded.

To resolve this, I hooked the route system for previous page to
not unload until the new page is loaded and the new page is downloaded.
( https://github.com/hmmhmmhm/svelte-spa-chunk/blob/master/Chunk.svelte#L10 )

Detection of whether or not to switch new pages can be operated
on the assumption that the page components are not recycled.

**Comment by hmmhmmhm** [comment]
I think some recent changes in grammar are causing this difference.

**Comment by ItalyPaleAle** [comment]
This was a real heisenbug!

I've looked into this quite a bit, and I also noticed that the issue isn't with the route`/a`, but with any third route you open. For example, if you start (refresh page) from `http://localhost:8080/#/b/blabla` and then click on the colors twice, it will show a white page too.

Lots of debugging later, it seems that the issue is with concurrency because of the `out:flashPrevent` in the `Chunk.svelte` file of your module `svelte-spa-chunk`. If you remove that line, everything works.

Additionally, even without removing that line, if you add `{@debug params}` before `<svelte:component this={component} {params} />`, which causes the browser's debugger to launch and so pauses the execution, everything works well.

I'm not really sure how to fix this, but it is a bug with `svelte-spa-chunk`, and it's a concurrency issue (*and we all know 99% of heisenbugs are concurrency issues* :) ). I'm quite confident that this is not a bug with the router itself, as the router seems to behave fine (looking at the console logs, the correct route is loaded, and the `routeLoaded` event is fired correctly).

Probably, the view is not being un-mounted correctly. Remember that this router performs all operations to mount a route in the next tick (with `setTimeout` with a 0 timer).

The reason why it works for the first two clicks seems to be that for the first 2 links, the browser is fetching the route which is dynamically imported. In the other cases, then, the route is already loaded so it resolves right away.

By the way, version 2.0.1 had some minor changes that I don't think impacted this. However, in 2.0.1 the dependency on Svelte was upgraded too - wonder if that made a difference in your case?

**Comment by hmmhmmhm** [comment]
OK, I don't know exactly, I'll going to go back to tracking this issue when the my company works done. Thank you for checking.

**Comment by hmmhmmhm** [comment]
@ItalyPaleAle 

Hello, I found the cause when I came to work in the morning and looked at the issue. ( https://github.com/ItalyPaleAle/svelte-spa-router/commit/4d693798cfd74a3ab0fc6c3a848d386c53ad4727 )
The issue I tagged above is the cause, and I think the more accurate cause is the following.

```svelte
{#if componentParams}
  <svelte:component this="{component}" params="{componentParams}" />
{:else}
  <svelte:component this="{component}" />
{/if}
```

By the "if statement" used above, both types of
components available in the "if statement" are cached in the svelte.

If i modify the code as shown below, everything will work properly.

```svelte
<svelte:component this="{component}" params="{componentParams}" />
```

I can give a few more examples of problems arising from these issues.

could i remove if state or prevent the DOM
structure from being cached by svelte?

**Comment by ItalyPaleAle** [comment]
Ok, I understand.

That if statement was necessary because of #83, and I can't remove it.

It seems that only your specific code is impacted, however, in a narrow scenario: when there's a transition (doesn't happen if you remove the transition), and when the component is dynamically loaded.

What if this was an upstream issue with Svelte itself?

**Comment by hmmhmmhm** [comment]
okay, so I think I'll have to bypass this by implementing algorithms that are not affected by recycling... Thanks again.

**Comment by ItalyPaleAle** [comment]
If I could implement a fix in the router, any suggestion on what it could be?
