### ISSUE TITLE
Svelvet compatibility

### ISSUE THREAD

**Issue by MerlinB** [ItalyPaleAle/svelte-spa-router#92]
When trying to set up the router with https://github.com/jakedeichert/svelvet (Using https://www.snowpack.dev/ instead of Rollup/Webpack), it fails with the following traceback:

```
internal.js:1558 Uncaught Error: 'target' is a required option
    at new SvelteComponentDev (internal.js:1558)
    at new Home (Home.js:118)
    at Array.create_else_block (Router-c9751f2e.js:145)
    at create_fragment (Router-c9751f2e.js:287)
    at init (internal.js:1400)
    at new Router (Router-c9751f2e.js:683)
    at create_fragment (App.js:204)
    at init (internal.js:1400)
    at new App (App.js:577)
    at (index):17
```

Here is a simple Svelvet setup with the svelte-spa-router example page:
https://github.com/MerlinB/svelte-spa-router-example

**Comment by ItalyPaleAle** [comment]
Thanks. I've looked into this, but I am leaning towards thinking this issue is with [svelvet](https://github.com/jakedeichert/svelvet). It seems that when Svelvet compiles all components into ES Modules, but it's not working well with dynamically-loaded components.

Proof point: if in `Router.svelte` I replace:

```js
<svelte:component this="{component}" params="{componentParams}" />
```

with:

```js

<script>
import Home from '/Users/alessandro/Desktop/svelte-spa-router-example/src/routes/Home.svelte'
</script>
<svelte:component this="{Home}" params="{componentParams}" />
```

This works.

It seems that it just doesn't like dynamic modules?

Can you please try opening an issue there, and see if they can figure out what's going on. I'm going to close this issue for now, but if it does turn out that it's an issue with the router, I'll re-open it.

**Comment by jakedeichert** [comment]
Hey @ItalyPaleAle! I just dug into this over here: https://github.com/jakedeichert/svelvet/issues/69#issuecomment-602054402

Looks like the issue can be fixed on this side 😅 

Can you take a peek at my comment I linked ^^, i posted a solution there, which follows svelte's API docs.

> It seems that it just doesn't like dynamic modules?

Regarding this point, @MerlinB wasn't doing a dynamic import either. All the routes are [statically imported](https://github.com/MerlinB/svelte-spa-router-example/blob/master/src/routes.js#L6-L12).

**Comment by ItalyPaleAle** [comment]
@jakedeichert Thanks a lot for figuring that thing out! Silly mistake on my end.

I'll make the fix right now and work on a release today.

**Comment by ItalyPaleAle** [comment]
@jakedeichert I just did the change but it actually doesn't work. You can see that the code compiles, but no component is loaded in the router. I'll have to revert the change...

**Comment by jakedeichert** [comment]
Yeah, that's my concern. That fix **works for svelvet**  and it follows [svelte's API docs](https://svelte.dev/docs#svelte_component). 

<img width="1183" alt="Screen Shot 2020-03-21 at 3 40 26 PM" src="https://user-images.githubusercontent.com/1631044/77235209-4d042e80-6b8a-11ea-81d3-bae60f087a14.png">


But for some reason, I assume your project has been working all along without that extra `.component` call. Your example project uses rollup and for some reason it doesn't require the `.component` property i guess?

If you want to do a quick workaround, you could check for the existence of the `.component` property and fallback otherwise (`component.component || component`). But something weird is definitely going on and i'm not sure what yet.

**Comment by ItalyPaleAle** [comment]
I think the Svelte API docs is showing an example in which the component is inside a dictionary. It's probably something unclear with the docs? Using `component` alone is the only thing that works for us.

Also, if you look at your screenshot in https://github.com/jakedeichert/svelvet/issues/69#issuecomment-602054402 you see that even there, no route is loaded. You can see the router, but it's not loading any component.

**Comment by jakedeichert** [comment]
> Also, if you look at your screenshot in jakedeichert/svelvet#69 (comment) you see that even there, no route is loaded. You can see the router, but it's not loading any component.

oh. Literally had no console errors at all when testing that.

I'll investigate more

**Comment by ItalyPaleAle** [comment]
The `/` route should look like the screenshot below. Your screenshot is missing the highlighted part, which is the `Home` component:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/43508/77235383-5d101400-6b72-11ea-9456-4ef1f292f1e0.png">

**Comment by jakedeichert** [comment]
@ItalyPaleAle @MerlinB Dev mode fix is documented here https://github.com/jakedeichert/svelvet/issues/69#issuecomment-602098919

Sorry about this @ItalyPaleAle 😓 


Thanks for the help debugging!

**Comment by ItalyPaleAle** [comment]
Thanks for working on this and for figuring out the issue! Glad you sorted it out (at least for dev mode :) )

**Comment by MerlinB** [comment]
Thank you both alot for your work in fixing this!
