### ISSUE TITLE
again: <component> was created with unknown prop 'params'

### ISSUE THREAD

**Issue by drop1down** [ItalyPaleAle/svelte-spa-router#98]
It seems that this bug is not fully fixed:
https://github.com/ItalyPaleAle/svelte-spa-router/issues/83

404-Components still have this issue for me

```
import NotFound from '../views/404.svelte'
const routes = {
	...
	'*': NotFound, //<<<<<<<
}
...
```

**Comment by ItalyPaleAle** [comment]
This is a good point but it's not something I can fix.

First, please note that it's just a warning that Svelte (not the router) emits, so: it won't break your app, and it's not something we can disable.

The fix for #83 consisted in passing the `params` prop only if there's a match in the path. That is, if your path is a fixed one (such as `/hello/world`) then there's nothing matched, so the router doesn't pass anything to the route. If there's anything that would create a match, then it's passed.

In the case of the `*` route, the router does create a `params.wild` prop, which matches the page that wasn't found. And that's passed to the component.

There's not much we can do there. It's not possible for a Svelte component to inspect another Svelte component and check if it exposes any prop (that is only possible if Svelte components are compiled as "custom elements" per https://svelte.dev/docs#Custom_element_API ).

You can only adopt a workaround, which can be one of:

1. Ignore the warning, given that it's just a warning anyways. It's annoying, but it won't break your app
2. In your `NotFound` component, expose the `params` prop: `export let params = {}`. You don't need to use that prop at all, but it being there will disable the warning.

I understand this is not ideal, but sadly this is not something we can change as it's how Svelte works.

**Comment by frederikhors** [comment]
This is very annoying and I think there must be a better solution.

**Comment by ItalyPaleAle** [comment]
@frederikhors I'm happy to accept PRs :)

**Comment by frederikhors** [comment]
> @frederikhors I'm happy to accept PRs :)

I wish I was capable of.

**Comment by frederikhors** [comment]
I opened this: https://github.com/sveltejs/svelte/issues/4652.

We'll see.

**Comment by ItalyPaleAle** [comment]
Thank you! I had opened another issue too asking for an API, but your approach seems better :)

**Comment by frederikhors** [comment]
What is your issue? Can you link here?

**Comment by frederikhors** [comment]
I <3 you and your router!

**Comment by ItalyPaleAle** [comment]
https://github.com/sveltejs/svelte/issues/4649

Thank you! :)
