### ISSUE TITLE
Caught exception while replacing the current page. If you're running this in the Svelte REPL, please note that the `replace` method might not work in this environment.

### ISSUE THREAD

**Issue by xellDart** [ItalyPaleAle/svelte-spa-router#99]
Hi I try to deploy my app to production using
 sirve public --host 0.0.0.0

but I get Caught exception while replacing the current page. If you're running this in the Svelte REPL, please note that the `replace` method might not work in this environment.

**Comment by ItalyPaleAle** [comment]
Can you share some code to reproduce this?

Also, what browser is this happening in?

**Comment by xellDart** [comment]
In all browser, my code is:


`const route = (component) => {
    return wrap(
        component,
        () => {
            return get(access) === ""
        },
    )
};

export const routes = {
    '/':  wrap(
        Principal,
        () => {
           return get(access) !== ""
        },
    ),
    '/register': route(Register),
    '/reset': route(ResetPassword),
    '/company': Company,
    '/login': route(Login)
};
`


and catch events

<script>
  import Router from "svelte-spa-router";
  import {replace} from 'svelte-spa-router';
  import { routes } from "./router";

  function conditionsFailed(event) {
    if(event.detail.name === 'Principal')
      replace('/login');
    else replace('/');
  }
</script>

<Router {routes} on:conditionsFailed={conditionsFailed} />

**Comment by ItalyPaleAle** [comment]
I'm sorry, I will need more code to be able to replicate the issue. This is missing the definition of all components.

Any chance you could create a repo that contains just enough code to replicate this?

In any case, note that `sirv` is not very stable (apparently), and there are known issues with using it with this router. Not exactly sure why, but myself and other users (see #22) have reported issues with it.

**Comment by ItalyPaleAle** [comment]
Can you try using a different server rather than sirv? For the sample, we use [serve](https://github.com/zeit/serve), which seems much more stable.

When running apps in production, most users prefer to use a "regular" web server (something like nginx), rather than a Node.js app, for various reasons, including security and performance. Many users that build SPAs with this router also deploy them on object storage services.

**Comment by ItalyPaleAle** [comment]
@xellDart did using a separate server fix the issue?

**Comment by xellDart** [comment]
Sorry, I can't fix this

**Comment by ItalyPaleAle** [comment]
I want to help you but I need more information :)

What have you tried?

Can you share a repository with just enough code to reproduce this?

**Comment by xellDart** [comment]
this is my code https://gitlab.com/xellCoders.go/nebulaadmin

**Comment by ItalyPaleAle** [comment]
@xellDart I am getting a 404 on that link

**Comment by ItalyPaleAle** [comment]
I figured the issue. It's not the server.

In your `App.svelte`:

```js
function conditionsFailed(event) {
    if(event.detail.name === 'Principal')
      replace('/login');
    else replace('/');

  }
```

This is causing a redirection loop when the app is compiled for production. The reason is that when the code is minified, the class name changes and it's not `Principal` anymore. This doesn't happen in development because the code isn't minified.

How you can fix it: rather than relying on `event.detail.name`, pass custom user data (see: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Advanced%20Usage.md#route-pre-conditions )

What I need to do: document that the name of the component might be different when minification runs, so users shouldn't rely on that
